package str

var (
	// Lowers ...
	Lowers = "abcdefghijklmnopqrstuvwxyz"
	// Uppers ...
	Uppers = "ABCDEFGHIJKLMNOPQRSTUVWXYZ"
	// Letters ...
	Letters = Lowers + Uppers
	// Digits ...
	Digits = "0123456789"
)
